### ISSUE TITLE
Definition of Done checklist

### ISSUE THREAD

**Issue by dublinsubway** [dublinsubway/software-qa-handbook#23]
Small checklist ensuring everything is taken care of. Responsible: @katieflynn1 

How to work with this:
- Answer the questions stated in checklist points
If no, comment what's wrong/create a PR to develop and fix it yourself. If you want someone to do it, you can either let the person know in the Whatsapp group or post a reply here and tag people (eg @dublinsubway ).
If yes,
- Click "Edit" in top right corner 
![image](https://user-images.githubusercontent.com/61555192/228264354-a5c88c8b-b8be-4ef1-9ba5-97afd3052c9a.png)
- Change `[ ]` to `[X]` or `[x]` to tick the box that's okay
- Save the changes

When everything is ticked, also let us know by commenting this list; that would mean we're ready to submit the assignment.

Checklist:
* [x] Table of contents
  * [x] Does readme ToC looks okay and all links work?
  * [x] Do links work throughout whole handbook?
 * [x] Introduction - does it looks and reads okay? Any typos or possible amendments?
 * [x] Data for developers themselves (scrum, reviews, change management)
   * [x] Is the word count between 500 and 1000?
   * [x] Does it reads okay? Is it understandable, not boring and not too technical?
   * [x] Is markdown layout okay?
   * [x] Do we have at least 5 references and are they good?
   * [x] Are pictures attached correctly?
 * [x] Final word - is it fine?
